default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: serviceseeking_todo_development

test:
  <<: *default
  database: serviceseeking_todo_test
